version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.1
    commands:
      - echo Setting max listeners limit...
      - node -e "require('events').EventEmitter.defaultMaxListeners = 100;"
      - echo Installing NPM dependencies...
      - npm install --verbose
  build:
    commands:
      - echo Building the React application...
      - npm run build
  post_build:
    commands:
      - echo Build completed, uploading to S3...
      - aws s3 sync build/ s3://existnchill.com --delete

artifacts:
  files:
    - "**/*"
  base-directory: build
